version: '3.8'

services:

  postgres_container:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "8080:80"

  ingestion_script:
    build:
      context: .
      dockerfile: Dockerfile-ingestion
    depends_on:
      - postgres_container
    env_file:
      - .env
    # Give enough time for the Postgres container to initialize
    restart: "on-failure: 5"

